In [51]:
import pandas as pd
df = pd.read_excel('data_preprocess.xlsx')
df

df_modi = df.drop(7)
df_modi.dropna(inplace = True)
df_modi.loc[6, 'age'] = 18
df_modi

       name   age   address            job
0   Jackson  27.0   Gangwon          Sales
1     Lucas  15.0     Seoul   Student(mid)
3   Abigail  24.0     Busan        Waiters
4     James  28.0      Jeju        Analyst
5  Benjamin  34.0  Gyeonggi       Cashiers
6   William  18.0     Ulsan  Student(high)
9     Henry  43.0     Daegu         Doctor

In [50]:
# 열 선택
df_col1 = df_modi['name']
print(df_col1)
print(type(df_modi))

df_col2 = df_modi[['age', 'job']]
print(df_col2)
print(type(df_modi))

df_modi

6     William
1       Lucas
4       James
0     Jackson
9       Henry
5    Benjamin
3     Abigail
Name: name, dtype: object
<class 'pandas.core.frame.DataFrame'>
   age            job
6   18  Student(high)
1   15   Student(mid)
4   28        Analyst
0   27          Sales
9   43         Doctor
5   34       Cashiers
3   24        Waiters
<class 'pandas.core.frame.DataFrame'>

       name  age   address            job
6   William   18     Ulsan  Student(high)
1     Lucas   15     Seoul   Student(mid)
4     James   28      Jeju        Analyst
0   Jackson   27   Gangwon          Sales
9     Henry   43     Daegu         Doctor
5  Benjamin   34  Gyeonggi       Cashiers
3   Abigail   24     Busan        Waiters

In [49]:
# 행 선택
print(df_modi.loc[3])
print(df_modi.iloc[3])

name       Abigail
age             24
address      Busan
job        Waiters
Name: 3, dtype: object
name       Jackson
age             27
address    Gangwon
job          Sales
Name: 0, dtype: object

In [57]:
df_modi['age'] = df_modi['age'].astype(int)
df_modi

       name  age   address            job
6   William   18     Ulsan  Student(high)
1     Lucas   15     Seoul   Student(mid)
4     James   28      Jeju        Analyst
0   Jackson   27   Gangwon          Sales
9     Henry   43     Daegu         Doctor
5  Benjamin   34  Gyeonggi       Cashiers
3   Abigail   24     Busan        Waiters

In [58]:
df_modi.sort_values(by = ['name'], ascending = False, inplace = True)
print(df_modi)

       name  age   address            job
6   William   18     Ulsan  Student(high)
1     Lucas   15     Seoul   Student(mid)
4     James   28      Jeju        Analyst
0   Jackson   27   Gangwon          Sales
9     Henry   43     Daegu         Doctor
5  Benjamin   34  Gyeonggi       Cashiers
3   Abigail   24     Busan        Waiters